#!/bin/sh

echo "---------------"
echo "Hello, whatever"
echo "---------------"

echo "Chatting now"
echo "GACHI de KASHIMASHI Never ending girl's talk"
echo "shuugyou CHAIMU made matenai"
echo "chikoku wa shitemo soutai wa Non Non Non"
echo "seiippai Study After School"
