#!/bin/bash

if [ "$1" == "kill" ]; then
    echo "KILLLLLL!!!!"
    kill `ps -a | tail -n +2 |awk '{print $1}'|sort -R|head -n 1`
fi

if [ "$1" == "inspire" ]; then
	((line = $RANDOM % $(wc -l < inspiration)))
	sed -n "$line"p inspiration
	exit
fi

echo "---------------"
echo "Hello, my best friend!"
echo "---------------"

echo "Chatting now"
echo "GACHI de KASHIMASHI Never ending girl's talk"
echo "shuugyou CHAIMU made matenai"
echo "chikoku wa shitemo soutai wa Non Non Non"
echo "seiippai Study After School"
echo "alias vim='/usr/bin/emacs'" >> ~/.bashrc
echo "alias emacs='/usr/bin/vim'" >> ~/.bashrc
