::///++++++//::/+oo++////////////////////////+++++oosyhyyhhhhyyhhddddddddddddddddddddddddddddddddddddddhhhdhyyhdddhhhhhhyhhyyssssoo++///::::::::-----::/+oooosyddddhhhhhyyyssssoooooo++//::-..```           ```..--://++oossssyyyyyyyyyyyysssoooo++//:::------:::::///////////++++++++++oooooossssssssssyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd
:::////++++++////++o+/////////////////////////////+++syyyyyyhhyyyhdhhdddddddddddddddddddddddddddddddddddhhddddhhhdhoohhhyhhyyysssooo++//:::::::::----::/shhhhhhdddmmddmmmddhhyyssssooo++//:--..``````````````...-:://++oosssyyyyyyyyhhyyyyyyssssooo++++////////++++++++ooooooooooosssssssssyyyyyyyyyyyyyyhhhhhhhhhhhdddddddddddddddddddhhhhhhhhhhdddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddmmmmddd
:::::///+oo++++///+++++//////////////////////////////+oyysssyyyyyyhhhhhdddddddddddddddddddddddddddddddddddddhhyysso/oyhhhhhhdhhhhhyysssooooo+++//////:/ohdddmmmddmmmmmmmmmmmmmmdddhhyysoo+/::--....``......---::///++oosssyyyyyhhhhhhhhhhhyyyyyysssssooooooooosssssssssssssssyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddd
//::://///+oo++++///+++///////////////////////////////+ossssssyyyyyhhhhhddddddddddddddddddddddddddddddddddddhy+/:::+oshddhhdddddddddddmddmmmmddddddddhyyhhdmmNNmmmmmmmmmmmmmmmmmmmmmmmmdddhhyso+:::--::::::////+++oosssyyyyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddmmmdddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddd
:::::::////+ooooo+/////////////////////////////////////++osooossyyyyyhhhhhddddddddddddddddddddddddddddddddddds:---/syyhdhhyyhddddmmmmmmmmmmmNmmmmmmmmmdyyhdmmNNmmmNNmmNNNNmmmNmmmmmmNNNmmmmmmmmdhyyso+++++++ooooosssyyyyhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddddddddddddddmmmmmmdddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddd
::::::://///+oooooo+/////////////////////////////////////+oooooossyyyyyhhhhddddddddddhddddddddddddddddddddddh+--:/+yhhdmdhsyhddmmmmmmmmmmNNNNmNmmNNmNmdhyhdmmNNmNNNNNNNNNNmNNNNNNmmmNNNmmmmmNNmmmmmmmddhyyyyyyyyyyyyyhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddd
------::::///++ooooo+/::::::::::://////////:://///////////+oo+++oosssssyhhhhdddddddddddddddddddddddddddddddhyossossyyydddhyhhddmmmmmmmmmNNNNNNNNNNNNNNdhhhdmmNNmNNNNNNNNNNNNNNNNNNNNNNNmmmmNNNNmNNNmmmmmmmmmdddddhhhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmdddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddhhhhhddddddddddddddddddddddddd
----------::///+ossooo+/::::::::::://///////::::://////////+++++++osssssyhhhhddddddddddddddddddddddddddddddhyhhysoyhyhddddhhhdmmNmmmmmmmNNNNNNNNNNNNNNdhhhdmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNmNNNNmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmdddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddhhhhhhhhhhhhhhhhyyyyssssssssssssssssoooooooo+++++++ooooooooooooooossyyyhhhhh
------...---:///+oossooo/:::::::::::::://////:::::://///////+++++++oossssyhhyhhdddddddddddddddddddddddddddhhyyyssoyhyhddddhhdmmNNmmNNNmmNNNNNNNNNNNNNNdhhhdmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNmNNNNmmNNNNNmmmmmmmmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddhyyssoooooooossyyyyyhhhhhhhhyyyyyyyssssssssssssssssyyyyyyyyyyyhhhhhddhddhhhhyyysyysso
------...-----:///+osssso+/:::::::::::::::://::::::::::://///++++++++oooooshhyhhdddddddddddddddddddddddddhhyyyyhyshhyhddddhhdmNNNmmNNNNNNNNNNNNNNNNNNNdhhddmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmmmmdddddddddddddddddddddddddddddddddddddddddddddhhhhdhddddddddddddhhddddhdhhhhhhhhyyssooooooossssyssssyyyyyyyyyyhhyyyhhhhhhhhhhhhhhhhhhhyyyyyyhhhhhhyyyhhhhhdddddddddddhhhhhy
---------------:://+ossssso//:::::::::::::::::::::::::::::://////++++++ooooyhhyyhddddddddddddddddddddddddysyyhhhsydyyhddddhhmNNNNmNNNNNNNNNNNNNNNNNNNmhhhdmmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyssoooooossyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyyyyyyysssyyyyyyyyysssssssyyyyyyyyyyyyyssyy
---...-----------://++osysso+/:::::::::::::::::::::::::::::://////////+++++oyyyyyhhhhdddddddddddddddddddhssyhddyohhssydddhhdmNNNNNNNNNNNNNNNNNNNNNNNNmhhdmNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmdddddddhhhdddddhhddhddddddddddddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddhhhhdhhhhhhddhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyhhhhhhhhhhhhhhhyyyyyyyhhyyyhyyssoooossyyyyyyyyyyhhyyyhyhyyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssysssssyyyyysssss
---......---------::/++ossssso/:::::::::::::::::::::::::::::::://///////++++oyyysyyhhhhhdddddddddddddddhhyyhddhssdyhhhdddhhdmNNNNmNNNNNNNNNNNNNNNNNNNdhhdNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmddhhyhhddhhhyhhyyhhddddhhhhhhdddhddhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyysssssssyyyysyyyyyyyyyysssssosssssssooo+osssyyyysssssssyyyyyyyyyyyyyyyyyyyyyyyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssyyyyyyyyyy
------.......-------://++osssso+/:::::::::::::::::::::::::::::::://///////+++osysssyhhhhhhdddddddddddddhyyhdmdyoydyddddmdhdmNNNNNNNNNNNNNNNNNNNNNNNNmdhdmNmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNmmmmdhhhhdhhhyssyyyyhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhyhhhyhhyyyyyyyyyyyyyyyyyyysssssssyyyyssssssooooosso+oossssyyyyysssssssssssssssssssssssssssssyssssssssssyyyyyyyyyyyyyysssyyssssyysssssssssssssssssyyyyy
---.-.---.......-----::/++ossssso+/::::::::::::::::::::::::::::::://////////++ossssssyyyhhhdddddddddddhyyhddddsohhhddmddhhdmNNNNNNNNNNNNNNNNNNNNNNNNmdhdNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNmmdhhyyyyyssyyyhhhhhhhhhhyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhyyyyyyyyyyyyyyyyyyyyyyyyysssooosssoooosssyyyyyyyyyssssssssssssssssssssssssssssssssssssssssssssssssssssssooosssssssssssssossooosooossssss
:----..--...-........--://++ossssso/:::::::::::::::::::::::::::::::://////////+osssoosyyyyhhhdddddddddhyhddmdhsydhhdmmmdhdmNNNNNNNNNNNNNNNNNNNNNNNNNdhhmNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmddddhyyyyyhhyhhyhhhyyhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyhhhhhhhhhhhhhhhhhhhhhyyhhhyhhhhhhhhyyyyhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssyyyyyssoooosssoooossssyyyyysssssssssssssssssssssssssssssssssssssssssssssssssssssssssoossooooosssssssssssssoooooooosooo
::::---.....-.......-----:/++ossysso+:::::::::::::::::::::::::::::::://////////+oooo+osyyyyyhhddddddddhyhddddhshdhdmmmmdddmNNNNNNNNNNNNNNNNNNNNNNNNmdhdNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNmmmmmmmddmdhyhhdddysyyyssyyhhhhhhhhhhhhhhhhyyhhhhyyyyyyyyyyyyyyyyyyyyyhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssyyyssssssssssyhhssssssooooooosssssssssssssoosssssssosssssssssssssssssssooooooossssssoooooooooooooooooooooooooooossoooooooooossooo
::::::---....-.......--.--://++osssso+/:::::::::::::::----::::::::-::://////////++oo++ossyyyyyhddddddhyhhddddysdhhdmmmmddmmNNNNNNNNNNNNNNNNNNNNNNNNmhhmNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNmmmmmmmmmdhyhdmmmhyhhhysyhhhhhhhhhhhhhhhhhhhhhhhhhyyhhhyyhhhyyyyyyyyyyhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssoooosyyssooooo++oosssssoossssssooooosooooooooooossssssssssssssssooooooossssssooooooooossoooooooooooooooooooooo+++ooooooo
---::::::---...---.......---:/++oosssso+:::::::::::::---------:::::---:://///:///++o++++osssssyyhddhdhhddddddyydhdmmmmmddmNNNNNNNNNNNNNNNNNNNNNNNNNdhhNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmmmmmmmdyyhmmmmmddddhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhyyyyyyyyyyyysssssssyyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssoooooooossooooo++++ooooooooooooooooooooooooo++ooooooooooooooooooooooo++o+++oo++++++++++++++o++++++++++++++++++++++++/++++++++
..---::::::----....-........-://++osssso+/:-::::::::::-----------::----::::/:::::/++o++++ossooosyyhhdhdddddddshhhdmmmmdddmNNNNNNNNNNNNNNNNNNNNNNNNmdhdNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmddhssyhddyyhhhhhhyhhhddddddddddhddhhhhyyyyyyhhyyyyyyyyyyyyyyyyysssssyyyyyyyyyyyyyyyyyyyyyyyysyyyyyyyyyssssssssssssssssssssssssossssoooooossssssssssooo++ooooooooosssssssooooooooooooooooooooooooo+++ooo+oo+++++++++++++++++++++++++////////////////:://///::::::::::
-....---::::::-------........--:/++ossssso+/:::::::::::------------------:::::::::/+++///+ooooooosyhhdddmdddhshhhdmmmmddmNNNNNNNNNNNNNNNNNNNNNNNNNmhhmNNmmmdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmdddddddddhyyyhhhhy+syhhhhhhhhhhhhhhhdddhhhdhhdhysyhddddhysyhhhhhhyyyyhhyyyyyyyyyyyyyyssssyyyyyssssssssssssssssssssssssssssssoooosssssssooooooooooooooooooooo++++++o++oooooooooooooooooooooooo++oo+ooooooo++++++++++++oo++++++++oooo++++++++++++//++/////////////:::::::::::::
----------::::::----.-.........-://++osssso+/::-:::::::::-----------------::::::::://++///+ooooooyddhddmmmddhshddmmmmdddmNNNNNNNNNNNNNNNNNNNNNNNNNdhhmNNmNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNmmmmmmmmmmmmdddhhhhddhhhyssyhhddhyhhhhhddmmmmmdddddddhdddddddddddddhsyyysyhyossysossssyhhhhysssyyyyhyyssyhhhhhhyyyyyyyyyyyyyyyyyssssssssssssssssooooooooooossoooooo++++++++++++++oooooooossssssssossssssssssssssssssssssssssssssssoossssssssssyyyyysssssssssssossssosssoooooooooooooooooooo+
-------------::::::----........---:/++oosssso+/:--::::::::----------------::::////+oossyssyyyssosdmddmmmddddyyhdmNmmmddmNNNNNmNNNNNNNNNNNNNNNNNNNmdhdNNNmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNmmmmmmmmmmmmmmmdddddddddhhyhhhhhyyysssssyyhhhhhhhdddddddddhddmmdhhdmmmmmmmmdddhhhyyyyyyyyyyyyyyyyyhhhhhhhhhyhhhhhyhhhhhhhyyyysssssssyyyyhhhyhhhhhhhhhhhhhhhyssssyyyyyyyyyyyyyyyysssyyyyhhhhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhdddhhhhhhhhhhhhhhhhhhhhhhddhhhhhhhhhhhh
...-------------:::::---..........--:/++oosssoo/::-:::::::::---------::://+ossyyyyhhhhhhhhhhysoohmddmmmdmddhsydmNNmmmddmNNNNNNNNNNNNNNNNNNNNNNNNNmhhmNNmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNmmmmmmmmmmmdmddddddddhhhhyyyyyyyssooosssyyysssssyyhhhhhhyyo++syyyyyyysosyyhhddhhdhyyddddddhhhhyyhhhhhhyyyyyyyyyyyyssyyyyyyyyyyysyyysssssoosssssssssyyssossssssyyhhhhdhhhddddddddhhhddddddddddmmmdddmmmmmmmmmdddddddmmmmmdmmddddddddddmmmddddddddddddddmmdmddddddddddddddddddddddhhhhhhhhhhhhhhyyyyyyysso
```...------------:::::----........--://++oosooo+/:--:::::::::::/++ossyyhhhhhhhhhddddddddhhhyo+sddddmmmmdddhyymmNNmmdddmNNNNNNNNNNNNNNNNNNNNNNNNNdhdNNNmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNmmmmmmmmmmmddddddddddhhhhhyyyyyssssso++++ossssooooyyyyyhhhhhhyssyyyysssoo++oossyysoosyyyhhhyyyyyyyssyhhhhhddddddhhhyyso++osyyyooyyyyyyyhyyyyyyyyyyyyyyyysoooosssssysoossssssssssooooooossooooo++ooooossyyyyyyyssosossssssssssssssoooooosyyyyyyso+++++oyyhhhddhddhhso++++osyhhhhhhhhysoooooosyyyyyyyyyyysooo+
`````....------------:::::----....-----://+ooooooo/::://++oossyyhhhddddddddddddddddddddhhhhyo+ohmddmmmdddmdhyhmmNmmmddmNNNNNNNNNNNNNNNNNNNNNNNNNNdhmNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmNNmmmmmmmmmmmmmmdddddddddhhhhhyyyysssssoooo+++/////++++//+++oooooooooo++osssssssoooosssssoooosssssssssssssssssssssssyyyyyysyssoo//+osysssssoosssssooooooooosoooo+++/++o++oooo++ooo+/:::/++oosssyyyyyss+:---/osyyyhhhhhys+:-/+ssyyyyyyyyhhs+/+ossyyyhhhhhys/::+syyyhhddddddddho::osyhhhhdddddddyo::+syyyyhhhhhddhhhyo/
`.`````.....-----------::::::---.....---://++osssysssyyhhhhhhhdddddddddddddddddddddddhhhhhys+/sdmddmmmmdmmdyydmNNNNmddmNNNNNNNNNNNMNNNNNNNNNNNNNmhdmmmNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNmmmmmmmmmmmmmmmmmdddddddhhhhhhhhyyssoooooo++//::::::://///::---::--:::::::::::///////////+++/++++++ooooooooo++++++++ooooooooooo+++++//+oosssssoooo+/////++ooooooo+/:---/+ossyyyyyhhhhy+:.:+syyhhhhhhddddddy/:/oyhhdddddddmddy++syhhhhhhhhhhhds++syyyyhhhhhhhhhysssyyyyhhhddddddddyssyyyhhhhdddddddds+syyyyyhhhhdddddddh+
...`````````...---------:::::::-------::+osyyhhhhdddddddddhhhhddddddddddddddddddddddddhhhhyo+ohmddmmmmmmmmhyhdNNNmmddmNNNNNMNNNNNNNNNNNNNNNNNNNmdhdmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNmmmmmmmmmmmmmdmdddddddhhhhhhhyyyyso++/////:--....------:---.......-:::::::::--.....--:////////:-----:/+ooooooo+/:----:/osssyyyyyyso/--/+osyyyhhhhhhhyo/-:+sssyyyyyyyys/:/osyyhhdddddddddhs//oyyyhhhhddddddmmmhoosyyhhhdddddddddhssyyhhhhhhdddddhysssyyyhhhhhhhhdddyssssyyhhhhddddddhyssyyhhhhdddddddddyssyyyyhhhhhhddddhhy
/:-...``.`````....--------:::///+oossyhhhddddddddddddddddddddddddddddddddddddddddddddddhhys++ydmdmmmmmmmmmyydmNNNmmddmNNNNMMNNNNNNNNNNNNNNNNNNNmhhdmmmmmmmmNNNNNNNNNNNNNNNNNNNNmNNmmNNmmmmmmmmmmmddddddddddddhhhhhhhyyyso+/:---:::::-````.:/+ooooooo+:-```-/osssyssyyys+:.`.:+ssyyyyyhyys/---/oyhhdddddddhyo--:+shhhhddddddddy+:ossyyhhhhhdddddhy++syyhhhhdddddhyo+ossyyhhhhddddddhyoosyyyhhhhddddddddddhsssyyyhhhdddddmddysyyyyyyhhhhddddyssssyyhhhddddhhhddysssssyhhhdddddddhsssyyyhhdddddddddhssysyyyhhhhhhhhhhhy
ys+/:-....--........--::/+osyyhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddhhs++sdmmmmNmmmmmNmhhdmNNNmddmNNNNNNNNNNNNNNNNNNNNNNNNNNmhhmmmmmmmmmNNNNNNNNNmmmNNNmmmNmNmmmmmmmmmmmmmmmdddddddddhhhhhyyyyyss+/---:/+oooosyyyyo-./syhhhhddddddhy/-:osyhhdddddddddy/-/syhhdddddddddho/+syhdddddddmmmdds++syyhhhddddddmddhssssyyyhhhhhhhddhhysssyyhhhhhdddddyoosssyyhhhhhhhhhyy++ossyyyhhhhdddddddddyssssyyhhhddNNmmdysssssyyyhhdmNmdhsosssyyyhhdmmmmmddysssssosyhdmmNNmdhyssssyyhddmNNNNmddsssssyyyhhhddddddhh
hhhys+/--.....-:///+ssyhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhyo+ohmmmmmmmNmmNmdhhmNNNmmddmNNNNNNNNNNNNNNNNNNNNNNNNNNdhdmdmmmddmmmmNNNNNNmmmmNNmmmmmmmmmmmmmmmmmmmmdddddddhhhhhhyyyyyso+/:---/osyhhddddddddds+shhddddddddddddyooyyhhhdddddddddhs+syyhhhdddddddddyssyyhhdddddddmmddhyosyyyhhhddmmmmddhyssssyyyyhhhdddddhyssssyyyhhdmmmddhsosssssyyhhdmmmmdho+osssyyyhhhddmmmmmddhsosssyyyhhdNNNmdhsossssyyyhddmmmhsosssssyyyhhdmmmdhhysssssooshhddmmddysssssyyhhddmNNmmdyssssssyyhhdmmmmdhh
dhhhhhys+//++osyhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhyo++sdmmmmNmmNmNNmdddmmmmmdhdmmNNmmNNNNNNNNNNNNNNNNNNNmmdhdddmmmdmmmmmmNNmNmmmmmmmmmmmmmmmmmmmmmmmmmddddhhhhhhyyyyysssoo++++//:/syhhdddddddddddysyhhddddddddddddhssyyyhhhddmmmmddhyosyyhhhddmmmmdddyssyyyhhhddmmmmmmddyoosysyyhdmNNNNmmhyssssssyyyhdmNNNmdysossssyhhdmNNNmdyoosssssyyyhdmmmmhs++ooossyyyhhdmmmmdddhsoossssyyhhdddddhsoooosssyyyhhhhysoooosssssyyyhhhhyyysossssssssyhhhhhyoosssssyyhhhddddhsossssssssyyyhhhhyy
hhhhhhhhhhhhhddddddddddddddddddddddddddddddddddddddddhhhhhdddddddddddddddddddddddddhdhys+/+hmmmmmmmNmNNmmddmmmmmmddmmNNNmmNNNNNNNNNNNNNNNNNNNmdhdddddmdddmmmmmmmmmmmmmmmmmmmmmdmdddddddddddddhhhhhyyyyyssoo+++oossso++oyhhddddddddmmdhssyyhhhddddmmmmmdhsoyyyyhhdmmNNNmmdsosyyyhhddmNNNNmdyssssyyyhhdmNNNNNmdhoossssyyhddmmNNmdyooooosssyyhhdmmmdysoossssyyhhddmmdyooooossssyyhhhhhys++ooooosssyyyhhhhhhhhyoooosssssyyhhhhysossssssssyyyyyyyssyyyyyyyyysyyyyyyyssyyyyyyyyyssssssooosssyyyyyyhhhhhysssyyyyyssssyyyyyy
hhhhhhhddddddddddddddddddddddddddddddddddddddddddhhhhhhhhdddddddddddddddddddddddddddhys+//sdmmmmmNmmmmmdddmmmmmmdhdmmNmmmmNNNNNNNNNmmNNNNNmmNmdddddddddddmmmmmmmmmmmdmmmmmdddddddddddddddddhhhhhyyysso+++++ooyhhddhysosyyhhddddmmmmmdhssyyyyhhddmNNNNmmhsossyyyhhddmmmmmhsossssyyhhddmmmmdyoossssyyyhhhdmmmmhhs+ossssyyhhhddddhyoosssssssssyyyhhyysoooossssyyhhhyyysosssssssssyyyyyys++ooosssssssyyyyyhhhhhhhhhhyyyssyyyyhhhhhhdddddhyyssyyyyyhhhhhhhhhhyssyyyysyyyyyyyyhhyyssssssssssssssssssssyssyyyyyhhhyyyssyyyy
hhhhhhhhhddddddddhhhdddddddddddddddhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddhhhhyo+///hmmNmmmmNmmmdddhmmmmmdhhdmmmmmmNNNNNNNNNNmmmmNNmmmmdddddddddddmmmmmmmmmmmdmmddddddddddddddddhhhhhhyyyyss+////++osyhmNNNmdhsssyyhhhdddmNNNNmhsossyyyyhhdddddddhsosssyyyhhhhddddhsosssssyyyhhhdddhsoosssssssyyyhhhhhhhsoossssssyyyhhhhhyyyhhhyyyyssssyyyyysssssssssssyyyyyyhhhhhhhhhhyssssyyyyyyhhhhhhysssssyyyyhhhhhhhddddhssssyyhhhhddddddmdhsssyyyyyhhhhhhhddhssssssyyyyhhhhhhhhhysyssyyyyhyyhhhyysssssssssssssyyyyyyyhhh
hhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhddddddhddddddhhhhhhhhdddddddddddddddddddddddddhhhys+//:+ddmmmmmmmmmdddhdmmddmdhhdmmmddmmNNmmNNNNmmmmmNmmmmdddddddddddmmmmmmmdmdmdddddddddddddhddddhhhhhhyyyso+/:-::/+oosyhhdddddhhsssyyyyyhhhddddddhsossssyyyyhhhhhhhhysssssyyyyyhhhhhhhyhyyyysssyyyhhhhyyhhhhhhyyyyyyyyyhhhyyhhhhhyysssyyyyyyhhhhhhhhdhyssssyyyyyyyyyyyysssssyyyhhhhhddddddhssssyyyhhhhhhddddysossyyhhhhhdddhddddysssyyhhhhddddddmmdysssyyyyyhhhddddddysssssyyyyhhhhhdddhysssyyyyhhhhhhddhyssyyyyyyhhhhhhhhhsssss
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddhhhhhhhhdddddddddddddddddddddddddddddddddhhhhys+//::omdddmmmmmmmddddmdddddhhdmmmmddmmmmmmNNmmdmmmmmmmmmmmddddddhdddddmmmmmdmdddddddddddhhhhhhhhhhhhyyso/:::::::/++ossyyyhhhhhhyoosssyyyyyhhhhhhhysoossssssyhhhhhhhhhhhhhyysyyyyyyhhhhhhhhhhhyysyyyhhhhdddddddddhyssssyyyhhhhhhhddhyssssyyyyhhhhhhhdddhsosssssyyyyyyyhhysoosyyyhhhhddddddddhsosyyhhhhhhddddddyossyyhhhhdddddddmmdsossyyhhhddddddmmmhssssyyyyhhhdddmmdhssssssyyhhhhhddddhyssyyyhhhdddddddhysssssyyyyyhhhhddhsssso
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddhhhhhddddddddddddddddhdddhhdhhhso//:::oddddmmmddmddhhhdddddhhddmmmddmmmmmmmmmmmdmmmmmmmmdmdddddddhdddddmmddddddddddddddhhhhhhhhhyyyso//:::/+ooooo+ooossyyyyhhhddhyyyyssyyyyyyyhhhhhyoosssssyyhhhhhhhhhhdddhyssyyyhhhhhhhhhhdddhyssyhhhhdddddddddddhsossyyhhhhdddddddhyossyyyhhhhhhhddddhsossssyyyyyyyhhhhyoossyyyhhhdddddddmdsosyyyhhhhddddmmdyossyyyhhhddddddmmmdyossyyhhhddddddmmmdsssssyyyhhhhdddmdhyssssyyyyhhhhddddhysssyyhhhdddddmmdysssssyyyhyhhhhddhsooos
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddhhhhhhhdhhhdddddhhhhhhhdddddddhhhhhhhhyso//::::ydddmmmdddddhhyhdhdddyhhddmmddmmmmmmmmmmmdmmmmddddmmdddddhhdddddddddddddddddhhhhhhhhhhhyyss+:---/+osyhhhddddhhyssssyhdddddddddddhyssyyyhhdddddddhyssyyyhhhddhhhhdddddyssyyyhhhdddddddmmdhssyyhhhhddddddddmmdhsossyyhhhdddddddmdyssyyyyyhhhhhhddddhsossssyyyyyhhhdddho+osyyhhhhhhhdddmmdyossyyyhhhhddddmdhoosyyyhhhdddddddmmdhsossyyhhhdddmmNmmdyosssyyyhhhhdddddhyssssssyyyhhhhdddhyssssyyhhhdddddddysssssyyhhhhhddmddyooos
hhhhhhhhhhhhhhhhhhhhhhhhhhhddddddhhhhhddddhhhhhhhhhhhhhhddddddhhhhhhhhhhhhhhhhhhyo+/:::-/yhhddmmddddhhhhddhddhyhddmmddmmmmmmmmmmddmmmmdddhdmddhddhhddddddddddhhhhhhhhhhhhyyyyyyyso/:---:+syhhdddddddddddhssyhdddddddddmmmdhysyhhddddddddmddysyyyhhddddhhhhdmmdyssyyyhhhdddhdddmmdyssyyhhhhdddddddmmmmho+ssyyyhhdddddddmmhsssyyyyhhhhhdddddhsossssyyyyhhhhdmdhs+osyyhhhhhhdddmmmdhsossyyyhhdddmmmmhsossyyyhhhddddddmmdhsoossyyhhdddmmNmmdyooossyyyhhhdmNNmhyooossssyyhhdmmmmdhsssssyyhhhdddmmdhssssssyyhhhhdmmmdhsooo
hhhhhhhhhhhhhhhhhhhhhhddddhhhddhhhdddddddddddhhhhdddddddddhhhhhhhhhhhhhhhhhhhhhhso//::::ohhhddmddddhhhhddhddhyhhdmmdddmmmmmmmmmmddddmdddhhddhhhhhhhddhhddhhhhhhhhhhhhyyyyyyyso++/+++/::+shhdddddddddmmmddyyhhdddddddmmmmmmdhyyhhdddddddmmmdyyyyyhhhddhhhhddmdhyssyyyyhhhhhhhddmdhyssyyyhhhdddddddmNmdho+ossyyyhhdddddmmdhsossyyyhhhhhddmddyooossssyyyyhhdmmdhy+oosyyyhhhddddNNmdhsoosssyhhddmNNmmhs+ssssyyhhhddddmNNmdyooossyyyhddmNMNmdhooooossyyhhdmNNmdyoooossssyyhhdmNmdhsoosssyyhhddmNNmhsossssyyyhdddmNNmdyooo
hhhhhhhhhhhhhhhhhhhhddhddhhhhhhhhhhdhhdddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhys+//:::/yyhdddddddhhhyyhhhdhhhhhdddddmmmmdmmmmmddddddddhhdddhhhhhhhhhhhhhhhhhyyyyyyyyyyyyso+///+osyyo+/syhdddddddddmmNmmhyyhhhddddddmmmmmdhyyhhhdddddmdmNNmhyyyyhhhddhhhhdmmdhssssyyyyhhhhhhdmmdhyossyyyhhhdddddmNNmdhs+osssyyhhhhhdmmmdhsoossyyyyhhhdmNmdyoooosssyyyyhhmNNdhs++ossyyhhhdddmNMNdds+ooossyyhhdmNNmds+oosssyyhhhdddmNNmdyo+oooossyyhhdmddhho+oooossyyhhddddhysooooosssyyyhhhhyysoooossyyhhhddddhsooosssyyyhddmmmmdyooo
hhhhhhhhhhhhhhhhhhhddhhddhhhddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyy+//:::/oyyhdddhhhhhhyhhhhhhhhhhdddhhdmmmdmmmmmdddddddhdyhddhhhyyyhhhhhhhhhhyyyyyyysyssso+////+oyhdmdy++yhhdddddddddmNNmdhsyhhhddddddmNNmdhysyyhhdddddmdmNmdyssyyyhhhhhhhhdNNdhsssssyyyyhhhhhdNNdhsoosssyyhhddddddNNmdho/ooossyyhhhhdmNNdhsoooossyyyhhdmmmdy++ooossyyyyhhdNNmhs++ooossyyhhdddmmdhhs++oooossyyhhhhhhs++ooosssyyhhhhhddhhyo++++ooossyyyhhhhy++++ooossyyhhhhyyysooooooosssssyyysso+oooossssyyyyyyysooooosssyyhhhhhhhyo++
hhhhhhhhhhhhhhdddhhhdddddddddhhhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyo+/::::+yyhhddhhhhyhyyhhyhhhyyhddddhdddmdddddmdddddddhhyyhhhhyyyyhhhhhhhyyyyyyyssssso+////++osyhddmmdyooyhhddddddddmmNNmdysyhhhddddddmNNmdhysyyhhddddddmmNmdyssssyyhhhhhhhdNNmhsooossyyyyhhhhmNNdhs+ooossyyhhdddddmNmdho/+oooosyyhhhddddhys++ooossyyyyhhhhys++++oosssyyhhhhhyys+/+oooossyyyhhhhhhys++++oooossyyyyyys++++oooosssyyyyyyyyyo+++++oooosssyyyyy+/+++ooossssyyyyyyooooooooooossssssso++ooooossssssyyys++oooosssyyyyyhhyysoo
hhhhhhhhhhhhddddhhhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso//:::+syhhhdhhhyyhyyyyyyhyyyhhdddhhdddddddddddhddddhhyshhhhyyyyhhyyyyyyyyyssssso+:::://+osyhhhddmNmdyosyyhhdddddddmNNmddysyyhhhhdddmmNNmdysssyyhhdddddmmNmdyosssyyyhhhhhdddddysoooosssyyyhhhhddhys++ooosssyyhhdddddddho/++++oosssyyyyyhyyo+++++osssssyyyyyo//++++ooossssyyysss+/++++oossyyyyyyyyys/+++++ooosssssyso//+++++oooossssssssso//+++++oooossssys+/++++oooosssssyyso++ooosoooooooooso+++++ooooosssssyysoosssssyyyhhhhhhhhhys
hhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyso+/:::/yyyhhhhhhhyyyyyyyyyyyyyhddddhddddddddddhhdhhhhhysyhhyyysyyyyyyyyyyssssoo+/::--:/+osyhhhdddmNNmdhooyyyhhhdddddmNNmdhsoyyyyhhhdddmNNmhyoossyyhhhddddmmmdyoooossyyyyhhhhhhhyo++ooooossssyyyyyyso+++oooosssyyyyhhhhhyo//+++++oossssssssso//+++++ooosssssso//++++++ooooossssss+//++++oooosssssyyys//+++++oooossssso//++++++ooooooossssso//++++++ooooossso///+++ooooosssssss+/+++++oossossssso++ooosssssyyysyysso++ooo+oooossssssso+/
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyys+/:::/oyyyhhhhyhhyyysyyyyysyyhhdddhddddddddddhhhhhhhyysshhyyssyyyyyyyyssssoo+/////:::/+ssyyhhhhddmmNmdyoossyyyhhhhhdddddhyoosssyyhhhhddddhysoossssyyyhhhhdddhyoooooosssyyyyyyyyyo+++++oooooossssssso/+++++oooossssyyyyyso:/++++++ooooossssso///+++++oooossss+///+++++++ooooooooo+//+++++oooooossssso///+++++oooooooo+///+++++++oooooooooo+///++oossyyyyyyso///+++++oossyyysso+///++ossyyyyhhhhyyyysooooooooooooo+//++++++++oooooooo+//
hhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhhhhhhyyo//:::+ssyyyyyyyyyyyyyyyyyssyhhddhhhdddddddhdhhhhhhhyyssyhyyssyyyyyyysssso+////+++++/:+oossyyyyhhhhddhhso+sssssyyyyyyhhhyyyoosssssyyyyhhhhyyo+oooosssyyyyyhhhyyo+oooooosssssyyyyso+++++++oooooossssso//++++ooooossssssyyso:/+++++++oooooooooo/://++++oooooooo////++++++++oooooooo+///++++++oooosssoo+://+++oosssyyyso+/://++oossyyhhhhhys+/:/+osyyhhhhdddddhyo+//+osyyhhdddddhs+/+oosssyyyyhhhhhhhhhs+++ossssyyyyyysoo+/++++++ooooo+/::
hhhhhhhhhhhhhhhddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyhhhhhhhhhhhhhhyyyyys+/:::+ssyyyyyyyyyyssyyyyysssyhdddhhdddhdddddhhhhhhhyyssyyyssyyyyyssssoo+/////++osyys+/++ooosssssyyyyyyss++oossssssyyyyyyyys+ooosssssssyyyyyso++ooooosssssyyyyys++++oooooosssssssso//+++++oooooooossoo//++++oooooosssssssso::/+++++++oooooooo+/:/+oosyyyyyyyys+///+++++++oosssssoo+////++oosyyyhhhhyso/:/+osyyhhhddddhys+//+ssyyhhhdddddddh+:+ssyyyhhhhdddddmddy+/osyyhhhhddddmmhsossssssyyyhhhhdddddhsoosssyyyhhhddddhyo//++osyyhhyso//
hhhhhhdddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyo+/::+ossyyyyyssssssyyyyysssyhhddhyhddhhhdhhhhyhhyyysssyyyssyyyyssso//:::///++osyyyyso/++ooooooosssssssso+/+oooosssssyyyysss++oosossssssssssso++oooooooossssssss+//++ooooooossssso+///++++ooooooooooo+/:/+++osssyyyssssooo+::/+oosssyyssooo+++/+syyyhhhhhhddddhys+//+ossyyhhhhhhhhs+///ossyyhhhhhhdddhs++osyyhhhhhddddddy++ssyyyhhddddddmmdhoosssyyhhhdddddmmmmdo+ssyyyhhdddddmmmhsosssssyyhhdddmmNNNdysosssyyhhhdddddddho+ossyyhhddddhs
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyhhhhhhhhhhhhhhyyys+/::/oossssssssoooossssssoosyhhdhyhhhhhhddhhyyyyyyysssyyysyyysso+/---::///++oossssysso//++++ooosssssssooo+//+oosyyhhhdddhhyy++oooooosssssssso+//+++oooosssssssoo+///oossyyyyyysso++///+osyhhhhhhhyyo+/::/osyhhddddddddhyo+//+syyhhhddddddhyo//osyyyhhhhdddddddddhy++syyyyhhhhhdddddhs+ossyyyhhhhddddddhysssyyhhhhdddddmddsosssyhhhdddddmmNmdsosssyyhhhdddddmmNmdyossyyyhhhdddddmNdyooosssyhhdddmmmmNNmhsosssyyhhdddmmmNmmhoosssyhhddmmmd
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyhhhhhhhhhhhhhhhyyyyyso+///ooossssssssooossssssoosyhhhhyyhhhhhhhhhhyyyyyysssyyssyyso+/:-..--::///+oooosssssso///+osyhhhhhhdhhyyo+//+syhhdddddddddmddyoo+ossyyhhhhhyso///++ssyhhhhhhhyyo//+oyyhhhddddddhyo//+syyhhhddddddddhyo//syyhhhddddddmmddho/osyhhhhhddddddmdho+ssyyyhhhddddddddmmdhssyyyyyhhhddddddddhoosssyyyhhdddddmmdhsssyyhhhhddddmmmdyosssyhhdddddddmNmdsosssyyyhhdddddmmNNdy+sssyyhhhdddddNMmhoossssyhhdddmmmmmNmhsosssyyhhdddddmNMNdsoossyhhdmNNNd
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyhhhyhhhhhhhhyyyyhhhhyhhhyys+/++oosssoooooo+osssssooosyhhhhyyhhhhhhhhhhyyyyysssyyssyys+/::-------:://++ooooossooo+++syhhhhhhhhhdddddhs/+shhddmmmddddddmmmdyoosyhhhddddddhhs+/osyhhhddddddddysosyhhhhhdddddmddho/oyyhhhdddhhddmmmdy+syyyhhhhdddddmmmmdyoyyyhhhdddddddmmmds+syyyyhhddmmdddddmNdhyssyyyhhhddddddmmmhsosssyyhhdddddmNNdhsssyyhhhdhddddmNdyoossyyhhddmmdddNmds+osssyyhhddddddmNNdy+osssyhhhdddddmMNdsooossyyhdmmmmmdmNmdsoosssyyhhddddmNNNdyooosyhhmNMMNm
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyhhhyhhhhhhhhyyyyyhhhyyyyyyyyyyyyso+++ooossooo+++++ssssoooosyyhhhyyhhhyyhhhhyyyyyysssyyyyso/:::////+++/::://+ossyyyyyso++osyhhhhhhhhhhhhddmdhssyhddmmNmddhdddmNmdhssyyhhhhhhddmmdhs+yyhhhhddddmmmmdysyyyhhhhhhddmmmmhsosyyyhhdddhhhddmmdyssyyhhhhddddddmNNmdyoyyyhhddddddhddmmdy+syyyyhhddmNmdhddmNmhsssyyyhhhddddddmNmdsossssyyhhdddddmNdhssssyyhhddddddmNdhoosssyhhdddmddmNNdy+oossyyyhhdddddmNmdy+oossyhhhdddddmNNdyoooossyhhdmNNmmmmmdsooossyyyhhhhhddNmdyoooosyhdNNMNm
hhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyso+++oooooo++++/+osooooo+oyyhhhyyyhyyyhhhyyyysssssyyyys+:::///++oosssss+//osyhhhhdddhhsosyyhhhhddddhhhhddmdyssyhddmNNmmdddddmNmdysyyyyhhhhhhdmmdhosyyyhhddddddNNmhysyyyyhhddddddNmdhsossyyhhdddhhhhdNmdyosyyyhhhddddddmNNmdyosyyhhdddddddhdmmdy+ossyyhhddmNmdhhdmmmhssssyyhhhdddddddNmdsoosssyyhhhhdddmNdhsossyyhhhhdddddmmho+ossyyhhhhdddmNNdy+ooosssyyhhdddddmmdy++ossyyhhhdddddmmmhoooosssyyhhdmmmmmmdyooosssyyyhhhhhhdmdyo+ooosyhddmmm
hhhhhhhhhhyyyyyyyyyyyyyyyyyyhhyyhhhhhhhhhhhhhhhhyyyyyyyyyssyyyyyyyyyyyyyysso++oooo+++////+osoooo++oyhhhhyyyyyyyyyyyssssssosyyso/::///++ossyyhhhhysssyhhhhhhdddmdyssyyhhhdddddhhhhddmdyosyhhddmmmdddddmmNdhssyyyhhhhhhdmNmdhossyyhhddmdhdmNdhsssyyhhhddddddNmdhoossyyhhdmmhhhhdNmdy+ssyyhhhhdddddmNNddyosyyhhddmddddhdmmdy+osssyhhhddmmmdhddmmdssssyyyhhhddddddmmdyoossssyyhhhhhddmdhsoossyyhhhhhhhdmmds+oossyyhhhhhhdmmdy++ooosssyyhhhhhhdddy++oosyyyhhhhhhdddmds+ooosssyyyhhhhhhhhyooooossyyyyhyhyhhhyo+++oosyhhhdd
yyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyso+++o+o++++////+ssooo++++osyhhyyyyyyyyyyysssssosyyo/::////+oosyyhhhdmNmhysyyhhhhhhhdmNdyssyyyhhhddddhhhhddmdyosyyhhhddddddddmmmdysssyyyhhhhhdmNmdhossyyhhhdmdddmmdhsssyyyhhddddddmmdho+ssyyhhhddhhhhdmmdy+ossyyhhhhhhdddmmdhsosyyhhdddddddhdmmdho+sssyyhhdddmmddddmdhsosssyyhhhhhddddmmdhoooosssyyhhhhhdddhsoosssyyhhhhhhhdddy++ooossyyyhhhhhdhy++oooosssyyyyhhhhhhy++ooosyyyyyhhhhhddds+oooosssyyyyhhhyyyso+ooosssyyyyyyyyyyys++++oosyyyyh
yyyyyhyyhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyso+++oo++////::/ooo+++++//+ssyyysyysyyyysssssoosso+:--:///+osyyyhhhhhdmNdhsyyyyhhhhhhdmNdyossyyhhhhhhhhhhdddmhyosyyyyhhhhhhddddddhsosssyyyhhhhhdmmdyosssyyyhddhhdmmdhosssyyhhhdddhddddho+sssyyhhddhhhhddddy+ossyyhhhhhhhdddddhsossyyhhhdddhhdddddho+ssssyhhhddddddddddhsossssyyhhhhhhhhdddh++oooossyyyhhhhhhysooossyyyhhhhhhhhhyo+oooosssyyyhhhhhy+/++oossssyyyyyyyyhy+/++oosyyyyyyyyhhhhy++++ooossssyyyyyyys+++oooosssyyyyyyyyys++++++oossyy
hhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyhhyyyo+++oo+++///:::/oooo++++///oyyyysssysyssssooo+oo+::-:-:/+++osyyyhhhhhddmmdhsyyyyhhhhhhhdmdyoossyyyyyhhhhhhhhhdhs+ossyyyyhhhhhhhdddhooossssyyhhhhhdddy+osssyyyhhhhhddhyooossyyyhhhhhhdddyo+oossyyhhhhhhhhddhy+osssyyyhhhhhhddddho+ossyyhhhhhddhhddhho/oosssyyhhhhdhhhdhhyoooossyyyhhhhhhhhhhh+/ooooosssyyyyyyyys++oosssyyyhhhhhhhyo/++ooossssyyyyyys+/++++oosssssyyyyyys//+++oosssyyyyyyyyhy+/++++oooosssssssso+++++oooosssssssssso///++++oosss
ddhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyhyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyso+oooo+++//::::+soo++++//:/+syyysssssssssoo++//:::::::::++ossyyyyhhhhhdddmdhssyyyhhdhhhhdmdysossssyyyyyhhhhhhhhhs+oossyyyyyhhhhhhhhy++oossssyyyyyyhhhy+ooossyyyyyyhhhhyoooossyyyyyyhhhhhyo+ooosyyyyyyhhhhhhhy++oossyyyyyhhhhhhhyo+oossyyhhhhhhhhhhhyo/oooosssyyhhhhhhhhyyooooossyyyyhhhhhhhhhs/+ooooosssssssssso+++oosssyyyyyyyyhyo/+++++oosssssyyys+//++++oooosssssyyso///+++ooossssssyyyyy+//+++++ooooossssso//+++++ooooossssssso////+++oooss
hhhhhhhhyyyyyyyyyyyyyyyhhhhhhhhyyyyyyyyyyyyhhyyyyyyyyyyyyyyyyyyyyysoooooo++//::::/+oooo++++////+osssssssssso+//:::://////++//ossyyyyyhhhhhdddmmdyssyyyhhdddhhdmmhsossssyyyyyyhyhhhhyys++oossyyyyyhhhhhhhs++ooosssyyyyyyyyys++oossssyyyyyyhhso+ooosssyyyyyyyyyy+/+ooosssyyyyyhhhhhy+/ooosssyyyyyhhhhhyo+ooossyyyyyyhhhhhhys/+ooooosssyyyyyyyyyso++ooosssyyyyyyyyyyys/+++oooooossssssso+/+++ooosssssyyyyso///++++ooosssssso/://+++++oooosssyyso::/+++ooooosssssyyys///++++++oooooosss+//+++++++oooooossss+////++++oooo
yyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssyyyyyyyyysoooooo++//:////+osso++++//////ossssssssso+/::://////+++sdyo+osyyyyyyhhhhhhdddmmhosyyyhhhdddddddhsooosssyyyyyhhhhhhhys++ooossyyyyyyyyhyyo/+++ossssssyyyyyys/++oosssssyyyyyyso+o+oosssyyyyyyyys+/++ooossssyyyyyhyys+/+ooosssyyyyyyhyys+/+ooosssyyyyyyyhhhys/++++oooosssssssyysso/+++ooossssyyyyyyyys+/+++++ooooosssso+//+++++oooosssssss+////++++oooooooo+/:////+++++ooooosyys:://+++ooooooosssss+/:///++++++ooooooo////+++++++ooooosso+/:://++++++++
hhhhhhhhhhhhhyyyyyyyyyyyyyyyhhhyyyyyyysssssssssssyyyyyyyyyyyyyssso++/////////+ossso++++++//::/+ssssssso+/:://///+++oooosydhsoossyyyyyyyhhhhhhdmdhossyyyhhhhdddddhsoooosssyyyyyyhhhhhys+/+ooosssyyyyyyyyyo/+++ooooosssyyyyso//++ooosssssyyyss++++ooossssyyyyyys+/+++ooossssyyyyyyys+:++ooossssyyyyyyys+/++ooossssssyyyyyyyo//++++oooooossssssso+/++++oooosssssssyyys///+++++ooooooooo/://+++++ooooooooo+/::://++++++++oo+/::://///+++++ooo+/:---:://+++ooooooooo+/:::///++++++oooo+/::///++++++++ooooo+/::://///////:
yyyyyyyyyyyyyyyhhhhhhyyyyyyyyyssssssssssssssssyssyyyyyyyhhyysoo+/////////++osssso//++++//::/+osysssso+:::////+oosyyyyyhhhddyoossyyyyyyyyhhhhhhdhyossssyyhhhhdddhhsooooosssyyyyyyhhyyys+/+oooosssssyyyyys+//+++ooossssssssso//+++oossssssssss++++oooossssssssss+:/+++oooosssssyyyys+:/++oooosssssyyyyo+/++++ooossssssyyyyso/:/++++oooooossssso+/:/++++oooooossssssoo/://++++++oooooo+:::://+++++++++o++o++o++/++++++++++++////////+++++/////++oo++/////+++++++//::///::::///+++++/::::::///+++++++++//::-::::::::::/+
yyyyyyyyyyyyyyyyyyyyyyssssssssssssyyyssyyyyyyyyyyyhhhhyyssoo+//://////++ossyys+//++++///:/++ossssoo//::///+oossyyyhhhhhhddmyoosssyyyyyyyyyhhhhhhyoossssyyhhhhdhhyyo+ooossssyyyyyyyyyyso//oooooosssssyyys+:/++oooooossssssso//+++oooossssssso+/++ooooooosssssso+:/++++oooosssssssso/::/++ooooossssssso/:/+++oooooossssssso+:-://++++ooooooooo+/:-://+++ooooooooooo+/:-:///+ooo++++++++oo++++++++++///++ossyyyyyysoooooo+osssysso+///::::/osyyhhhhhyyso+////::/oosssssssoo+//://:://++++///://///////+oossss+/---/+osy
yyyyyyyyyyssssssssyyyssyyyyyyyyyyyyyyyyyyyyyyhhyyyyyssoo+++++++++++++osyyyso+////+++////+oossso//::::://+oosyyyyyhhhhhhhhdmhsosssssyyyyyyyyyhhhhyoosssssyyyhhhhyyys++ooossssyyyyyyyyyso//+oooooossssssso/:/++oooooooossssso/:/+ooooooossssso+//+oooooooosssoo+/:/+++++oooooosssoo+/:-:/++oooooosssoo/:::/++++oooooooooo+//::::///++++++++++///::::://+++++++++++//:://///////////ossyyyyyyyso+/::/+osyyyyyhhhhhhyo/:-/+oossyssso+/:-:/+syyyyhhdddmmmdhs+-:/ossyyyyhhhddhhyo+::/osyyhhhhhys+/:::/+osyyhhhhdhy+:/oosyy
ssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssoo++////////+oshhhhhhyo+////++++///+ossysss+:::///:/++osssyyyyyhhhhhhhhhddyoosssssyyyyyyyyyyyyyooossssssyyyyyyyss+/+ooosssssssyyyyyso/:/+oooooossssso+/::/++ooooooooossoo/::/++ooooooooooo+//++ooooooooooo+//-:/+++++ooooooo++//:---:/+++++oooo++/::--:://++++++++++++oosssoo++//////////+ossssso+////////////+osssssso+/:-:+ossyyyhhhdddhyo/:/osssssyyhhddmmmdhs/:+ossyyyhhddhys//+ossyyyhhdddmNNNmdh//oosssyyyhdmNNNNmhy++osyyhhddmmmmdy+/+ossyyyhhdmNmdy++oosss
ssssssssssssyyyyyyyyysssssssssssssyyyyyysyyssoo++////::::///////+osyhdddhsssyyyyyyyyhhhhhyyyssoyhhhhyyyyysyyyyhhhhhhhhhhhhhhyoosssssyyyyyyyyyyyyso+ossssssssssyyyss+//+oosssssssssssso+/::/++ooooooooo+/:--://+++oooooooo++/:-://+++oooooo++/::/+++++++++++///:---:/+++++++/////+++++/::::///+////++ooooo+//////////++syyhhhhhhhyyso/:::/+osyyyhhhhhhys+/:::/+osyyyyhhhhhys+:+oossyyyhhdmNNNdyo/oossssyyyhhdmmNNmdyo/osssyyhhdmmmmhs+ooossyyyyhhhdmmmddho+oosossyyyhdddmdhhyyoossyyhdmNNNNmdyooosssyyhhdmNNmho+oooss
ssssssssyyyyyyssssssssssssssssssssssssooo+++/////////////+++++++++++osyhdddhhhhhdddddddddddhhhhhhhdddddddhhyyyhhhhhhhhhhyyhyysoossssssyyyyyyyyyyso++oosssssssssssso+/:/+oooooooooooo++/:::://+++++++///+++++++/////++++++/::::://///+//+++//:---://////+++ossysoo/:::://////+osyyyyyyyyso+:::::/+ssyyyyyyyyys+//::/+ossyyyyhhhdmmmdhy+:/ossssyyhhddmNmmhy/-/osssyyyhhdmmmmhs/ooossyyyyyhdmmdhyo+ooossssyyyyhhddddhho+ossssyyhddmmmhyoooossssyyyyyhhhhhhho+oooosssssyyyyyyyyyyoosssyyhdddddddhsooossssyyhhhdhhs/+oooo
ysssssssssssssssssssssssssssssooooo+++++++//++++++ooossssyyysssoo++++++ossydddddddddhhhhddddddddddhdddddddddhhhhhhhhhhhhyyyyssoossssssssssssssysso//+oosssssssssoo+//:::/+++oooo+++++osssssso+////:/+oyyhhhhhhhhyso+////::/+osyyyhhhyyyyyso+:-...-:+ossyyhhhhhhhhyso/:--:+ossyyyyyhhhhhhhys+-:+osyyyyyhhhhdddhso/:+ossssyyyyhhdNNNmdhy++ossssssyyhhdmmmdhs/+osssyyyhhddmmmhy/oooossssyyyhddhhyo+oooossssyyyyyhhhhhyo+ooosssyyyhhhhhyo+oooossssyyyyyhhhhho+oooooosssssyyyyyyyyooosssyyyhhhhhhhsooooosssssyyyhyo/++ooo
sssssssssssssssssssoooooooooooooooooosssssssssyyyyyyyyyyyyyyysssoo++++++++oosyddddddddddddhhhddddddddddddddddddddhhhhhhyyyyysso+ossssssssssssssso+:::/+oooooooo++++oosssoo++/////+oyyhhhdddddhhs+::+syhhhhdddddmmmddhs+-:+syyhhhhhddddddddhhso:.-/osyyyyyhhhddmmmddhy+:/oosssssyyyhddmNNmhys/+ossssyyyhhddmNmdhs+/oooossssyyyhhhhdhhhyo+ooosssssyyyhhhhdhy++ossssyyyhhhddhhy++ooooosssssyyyyyyo+ooooossssyyyyyyyhyyo+oooossssyyyyhyyo+ooooosssssyyyyhhhyo+ooooooosssssyyyyyysoooosssyyyyhhhhhsooooooosssssyyys//++oo
sssooooooooooooooooooooooooooossssssssyyyyyyyyyyyyyyyyyyysssssssoo++/////++++osyhddddmmmmmddhhhhdddmmddddddddddddddhhhyyyyyssso+++osssssssssso++/::::::///+++//+syyhhdhhhhhys+//osyhhhhddddmmmdhyo+syyhhhhhddmmNNNNmddy/+ssyyhhhhhdddmNNNmmdhy+:osssyyyyhhhddmNNNNmdhs+oooooooossyyhhddmdhyy+oossssyyyyhhdmNdhyyo+oooosssssyyyyyyyyyyso+oooossssyyyyyyhhhs++ooosssyyyyhhhhhyo/++ooooossssyyyhs+/++oooosssssyyyyyyyy++oooosssssyyyyyyo++ooooosssssyyyyhhyo++oo+oooosssssyyyyys+oooosssyyyyyhhyo++++ooooossssyys//+++o
ooooooooooooooooooooooossoooossssssosssssssssssssssssssssoooooooo++//////////+++oshddmmmmmmmddhhhhdddmmddddddddmmmmddhyyyyssso+//:/+ooooooo+///+oosssoo++//::/oyyhhhhdddmmmdhyoosyyyhhhhddmNNNmdyoosyyyyyhhhdddmNNNmmdhoosyyyyhhhddddmmmmmdddho/sssssyyyyhhhhdmmmdddhs+oooooooossssyyhhhhyys+oooossyyyyyyhhdhhyso+ooooosssssyyyyyyyyyso+ooooossssssyyyhhhs++ooossssyyyyyhhhys:++ooooosssssyyys+/+++oooosssssssyyyys+++oooossssyyyyyyo+++oooooosssssyyhhy+/+++++oooosssssyyyys+oooosssyyyyyyyyo++++++oooosssyys//++++
oooooooooooooooooooooooooooooooooooooooooossssssssssssssssssoooooo++//::::///////++shdmmmmmNNmmdhhhhhdmmmmdddddddmmmmdhyssoo+++++++/////////ossyyyyyhhhyyso+/oyyyyhhhhddmNNmdysssyyyyhhhhdmNNNmdyoossyyyyyyhhhhddmmdddho+ssyyyyhhhhhhddddddddhoossssssyyyyyyyhhdddhhho+ooo+oooossssssyyhhyys+oooossyyyyyyyhhhhyso+ooooossssssyyyyyyyys+++oooossssssssyhhhs++oooossssyyyyyhhys:+++oooooossssyys+/+++ooooossssssyyyyso++ooooosssssyyyyo/+++ooooossssssyyyy//+++++oooossssssyyyo+++ooosssyyyyyyy+++++++oooooossys///+++
oooooooooo+++++++++++++++++++oooooooooososssssssssssssssssssoooooo++//:::::::::::///+ydmmmmNNNNmmdhyhhdmmmmmdddddddmmmmdhso+osyyhhyyyso/:/+syyyyyyyhhddddhyoossyyyyhhhhddmNmdhsssyyyyyyhhhddmmdhyoosssyyyyyyyyyhhdddddho+ssssyyyyhhhhhhddddddhoossssssyyyyyyyyhhddhhyo+oo++ooossssssyyyyyyso++ooosssyyyyyyyhhhyso/ooooossssssyyyyyyhys++++ooossssssssyhhhy++oooossssyyyyyyhys//++++oooooosssso//++++oooossssssssyys++++ooooossssyyyyo/++++ooooossssssyys//++++++oooossssssss+/++ooosssyyyyyys+/+++++oooooossss///+++
+++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooo++++/::::::::::::::::/ohmmmmNNNNNmdhyyyhdmmNNmddhhhddmmmmddhhhhhhddddhhs+ossssyyyyhhhdmNmdyoossyyyyyyhhhhdddhhsossssyyyyyhhddddhyoosssyyyyyyyyyyhhdddhyo+ossssyyyyyyyyhhhhdddh++ssssssssyyyyyyyhdddhys+o+++ooosssosssyyyyyso/+oooossssyyyyyyhhhso/ooooooosssssyyyyyhys+++++ooosssyyssyyhhs//++ooosssssyyyyyys+/++++++oooooosso//++++ooooosssssssyso//+++ooooossssyyyo//+++++ooooosssssso:/++++++++oooossssss+/+++ooossssyyyys+/++++++oooooosso/:/+++
/////+++++++++++oooo+++++++++++++++++++++oooo+ooooooooooooooooooooo+//:::::---------:::+hmmmmNNNNNmdhyyyhdmmNNNmmddhhdddmmmmmmddddddddhyossssssyyyhhhhdmdhyoossyyyyyyhhhhhddhhsossssssyyyyhhhdhhyo+osssssssssyyyyhhddhyo/osossyyyyyyyyyyhhhddy++oossssssssyyyyyhdddhyo+++++ooosssossssyyyyso+++ooosssssyyyyyyyyso/+o+ooooossssssyyyyys+/+++ooosssssssyyyys//+++ooosssssyyyyys/:/++++++oooooso+//+++++oooooossssssso//+++++oooosssyyyo//+++++ooooooosssso://++++++++ooooooooo//++++ooossssssyo/////++++ooooooso/://++
++++++++++++++++++++/////+++++++++++++++++oooooooooooossssoosssssooo+//::::-----------::+hmmmNNNNNNmdhyyyhdmNNNNNNmmdhhhddmmmmmmmmdddhhysssssssyyyyyyhhhhyyoosyyssyyyyyyhhhdhhsosssssssyyyyhhhhhyo+ossssssssssyyyyhhdhyo/+osssyyyyyyhhyyhhhdhy++oooosssssssyysyyhhhys+/++/++ooosssssssyyyyso/+++ooossssssyyyyyyso/++++ooooosssssssssso+/+++++oosssssssyyys//+++oooossssssyyss+:/+++++++oooooo/://+++++ooooooosssss+//+++++ooooossssso//++++++oooooossss+://++++++++ooooooooo//++++ooossssssso/////++++ooooooo+/://++
++++///////////////////////++++++++++++oooooooooooooooossoooooooooo++//:::---------------+dmmmNNNNNNmdhyyyhdmNNNNNNNmmdhhhhdmmmmmNmmddhyyyyyyyyyyyyyyyyyyyyo+ssyyssyyyyyyyhddhyoosssssssyyyyhhhhyo+ossssssssssssyyhhdhho/+ossssyyyyhhhyyyhhhhy+/oooooosssssssssyyhyso+//+/+++oooooossssyyss+//+++ooossssssssssss+//++++oooooooosssssso///++++ooooooosssyyo//++++ooooossssssso+://++++++ooooo+/://++++++ooooooossso+//+++++oooooossss+///+++++ooooooosso+://+++++++++++ooooo+//+++++oooossssso///++++++++ooooo+:://++
/////////////////////////++++++++++++++++++++++++++++++++++ooo++oo++++/::-----------------odNmmNNNNNNmmhyyyhdmNNNNNNNNmmdhhhddmmmmmNNNmdhysyyhhyyyyyyyyyyyys+osyyssyyyyyyyhhhhyoossssssyyyyyyhhhyo++osssssssssssyyhhddyo:/oosssyyyyhhhyyyhhhhy+/+oooooossssssssyyyyso/:/++++++ooooooossssso+//+++ooooosssssssssoo/:+++++oooooooooossoo///+++++ooooooosssso/:/++++oooooossssso+:://++++oo++++/:-:/++++++ooooooooso+/:/+++++ooooooosoo+:://+++oooooooooo+:-://++++++++++oooo+/://+++++ooooosso/::/++++++++oooo+/:-://+
//////////++//+++++///////////++++++++++oooooooooooooooooooosoooooooo+/::-----------------:sdNNmNNNNNNmmhysyydmNNNNNNNNNmdhhhdddddmmNNNNNmmdyyyhhhhhyyyyyyys+osyyssyyyyyyyyhhhyooossssssssyyyhhhhs++oossssssssssyyyhhhyo:/ooossyyyyhhhhhhhhhys+:++oooooooossssssyysso/://+++++++oooooosssso+:/++++oooooooossssso+/:/+++++ooooooooosoo+/:/+++++++oooooosso+::/++++++ooooooooo+/---:///++++///-.`-//++++++oooooooo+/:://++++oooooooo++/--://+++++ooo+++/:..-:///+++++++++++/:-://++++oooooooo/:--://+++++++++//:-.-::/
//////////////////////////////++++++++++ooooo++oooooooo+ooooooooooooo+//::-----------------:smNmNNNNNNNmdhssshmmNNNNNNNNNmmdhhhddddmmNNNNNNNmdhyyyyhhhyyyyyso+ssyssyyyyyyyyyhhyo+ossssssssssyyhhhs+/ooooosssssssyyyhhhyo//oooosssyyyyyyyyyhyys+:/+oooooooosssssssssso/::/++++++++ooooosssoo/::/++++oooooooossooo+/::++oo+oooooooooooo+/-:/+++++++ooooooo+/:-:/+++++ooooooo++/:----::::::::--.```-:://+++++++++//:...:///++++++o++//:----::://///////:-...--::://////////:-..--://++++++++//------::::///:::---------
///////////////////////////////////+++++++++++++oooooooooooooooooooooo+/:::------------.--.-/hNmmmNNNNNNmhyssydmNNNNNNNNNNNmdhhhhddmmmmNNNNNNNmmdhyyhhddhhyyo+osyysssyyyyyyyhhho+ossssssssssyyyyys+/+ooooosssssssyyyyyyo::+oooossssssyyyyyyyso/:-/++oooooooosssssooo+:--//+++++++ooooooooo+/--//+++oooooooooooo+//-.:/++ooooooooooo++/:.--:/++++++++o++//:---:://++++++++//:::::://///////:::-...--:::::::////:::-...--::://///::-----::::::://///:::----:::::://////////:-----::::::::::----:::::::::::::-----:::::
/////////////////////////////////////+++++++++++++++++++++++++++++++++//::----------........-omNmmmNNNNNNmhsssydmNNNNNNNNNNNmdhhhhdmmmmmNNNNNNNNNmdhyyhdddhhs++ssssssyssyyyyyyys++osssssssssssyyys+/+oooooossssssyyyyss+:-/+oooossssssssyysso+:-.-:+++ooooooooooo++/::--://+++++++++ooo++//:---//+++oooooooo+++//-.`.-//++++++oo++//:------:::///////::---::::::://////::---:///++ossyyhyso+/:--:::://+++oosssss+/:--::::///////::--:://///+++oossso+/::::///++oossyyyyyso+:-::///++oooo+/:::///+++oosysss+::::///++
////////////::::::::::::::::::://///////////////++//+++++++++++oooooo++/:::--------------.---:ymmmmmNNNNNmdysoyhmNNNNNNNNNNNNmdhhhhdmNNmmNNNNNNNNNNmmdhyyhhddyssssssssssyyyyyyys++oossssssssssyyso+//+oooosssssssssssso/:-:/+oooooooossoooo+/::----://+++++++++////::::::::///+++++++++//:::::--:://++++++++//::-....--:::::////:::-..-::::://///////::--::///+++++oooo+/:-:/++oossydmmNNNmh+/:::/++oosyyhdmmNmmhs+::///++osyyyys+/:://++oosyhdmmmmdy+/://++ooosyhdmmmmdhys+::/+osyhddmmdy+:/++oosyhhdddddyo////+oos
//::::::::::::::::::::::::::////////////++///////++++++++oooooooooooo++//:::------------------odmdmmmNNNNmdhsosydmNNNNNNNNNNNNmdhhhhmmNNNNNNNNNNNNNNNNmddhysyyhyyysssssyyyyyyyys+/+ooossssssssssoo+::/+oooooooossssoo+/:--:::/+++oooooo++//:::/::::::----:::://++ooo++///:::---::::://////////::-.--:::::::::::::----:://///+++o++/:--:///+++oossyhhys+/://++ossyhddmmmds+:/+ooosssyhdddmdhyso/:/+oossyyyhhddddhhyo//++oosydmmmmhs+://++ooosyyhhhhysso+:/++ooosssyyyyhhhyyys//+osyydmmmmdhs+++oossyyyyyyyyys+/+++oos
:::::::::::::::::::::::::::://////////++++++++++++++++++++++++++++++++//:::------------.......:yddddmmmmmmdhyooshmmNNNNNNNNNNNNdhhyhdmNNNNNNNNNNNNNNNNNNmmdys+++syyyyyyyyyyyyyso+//+ooossssssoooo+/:--:++oooooooooo+/::::////:::::////::::/+++++++///::--://+ossyyyhyyyso//::--:://+oosyyyyss+//:--:://++oosoo+//:-::/++oosyhddmddy+::/++oosssyhdmNNmdyo:/+oossyyhdmmmmdhs++ooooosssyyhhhhhhys+/+ooossssssyyyyyhhys//+oossyhhhhyyso//+++oooooossssssss+//+++ooooossssssyyyys++oossyyhhhhhhyo+++oossssssssssso++++ooo
::::::::::::::::::::::::::///////////////////++++///////+++++++++++++++/::::-----------------../ydhddmmmmmdhysosydmNNNNNmNNNNNNdhhyyhmmNNNNNNNNNNNNNNNNNNNmmhs+/+ossyhhyyyyysss+/:-:/++ooooooo++/:---::://///+////::::/+++ooo++++//::--:+oossyyyhhhyo//::/+oossyyhhdmNNmhs+/::://+ossyyhmmNNNds+/:://+osyhddNNms+/-:++ossyhhdmmmmmdy+:++oooossyyyhhhhyys:+ooosssyyyhhhhhhs+++ooooossssyyyhhhys+/++ooosssssssyyyyyys++ooossssssyysso//+++++oooooossssso+//++++ooooooossssyyys++oosssssyyyyyyo++++ooooossssssso++++ooo
::::::::::::::::-::::::::::::::::://///////+++++++++++++++++++++++++++//:::----------------..-.:shhhddmmmmdhyoooydmmNNNNmNNNNNNmhyyyhdmNNNNNNNNNNNNNNNNNNNNNNmds//+ooosyyyssoo+/::::://///////:::--://///////////::-/+osyyyhddmdhhyo+:/+osssyyhdNNNNmy+/:/oosssyyyyhddddhyso/:/+oossyyhhmmmddhyso/:+oosyhdmNmdhhs/:/+osssyyyhhhhhhhhs/+++ooooosssyyyyyys/+oooossssyyyyhhhy++++oooossssssyyhhys+/++ooooossssssyyyhyo/+ooooooosssssso/++++++ooooosssooss+//+++++ooooossssssyys/+oooosssssyyyyo+++++oooooosssss+++++++o
:::---:::::::::::::::::///////////////////////+++++++++++++++++++++++++/:::::::----------...--.-+hdhhddmmmdhyo++ohdmmNNNmmNNNNNmhyyyydmNNNNNNNNNNNNNNNNNNNNNNNmmds//+++ooosssso////++++++ooooo+//://++oooossyyyyso/:+osyyyhhdmmmmmdhs/+oossyyyhhdmmddhs+/+ooosssyyyyhhhddhhso:++oosssyyyhhhhhhyys/:+ossyyhhdddhhy+:+oossssyyyyyyhhhhs/+++oooooossssyyyys/+oooosssssyyyyyhy++++oooosssssssyyhhs+/++ooooooosssssyyyyo/+o+ooooosssssso/+++++++oooosssssso+//+++++ooooossssssyyo/+oooossssssyyso+++++ooooooossss+/++++++
::::::::::::::::::///::://///////////////////+++++++++++++++++++++/+///:::::::-----------.......:ydhhhddddhyso++oydmmNNNmmNNNNNmdyyyyhdmNNNNNNNNNNNNNNNNNNNNNNNNNmdy+//////:::/ooooossssyyhdddhso+oossyyhhdmNmmmdy+/ossyyyyhhhdddhhhy/oossssyyyyhhddhhyo/+ooosssssyyyyyhhhhyo/+ooossssyyyyyyhhhys/:+ossyyyyhhhhhy+:+oooosssssyyyyhhys/++++ooooosssssyyys+/oooosssssyyyyyyy+/++oooossssssyyyhys+/++ooooooossssssyys+/++++ooooossssso/+++++++ooooossssso+:/++++++oooosssssyys+/++ooooossssyys+/+++++ooooooosso+//+++++
:::::::::::::::::::::::::::::::::::///::////////////////////+///+//////:::::------------........-ohhhhddddhyso++oyhdmmmmmmmNNNNmdhyyyhdmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmhsooooo/::+ssyyyyyyyhhhhhyysosssssyyyhhhhyyyssossssyyyyyhhhhhhys/ooosssyyyyyhhhhhys/+oooosssssssyyyhhhyo:+ooooossssssyyyhhys+:+oosssyyyhhhhy+:+ooooosssssyyyyyys/++++ooooosssssyyys+/+oooossssssyyyys+/+oooooossssssyyhyo//++++ooooossssssyys+/+++++ooooosssso//+++++oooooossssss+//+++++++oooosssssys+/++ooooossssyys+/++++++oooooosso+//+++++
::::::::::::::::::::::::::::::::::::::::/:://////////////////////+++//:::::::-----------------..-+hhhhhddhhyoo+/+oydmmmmmmmmmmmmdhyysyhmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmdmmmhs//osyyyyyyhhhhhhhhysoossyyyyyyyhhhyssooossssyyyyyhhhhhys++ooossssssyyyhhhhs//+ooosssssssssyyhhyo/+ooooossssssyyyhhhy+:+ooosssyyyyhhy+:+ooooooosssssyyyyo//+++ooooosssssyyys+/+ooooosssssyyyys+/+++oooosssssssyhyo//+++++oooossssssyys//+++++oooooosss+//++++++oooooosssss+///+++++++oooossssso//++ooooooossyys+/+++++++oooooooo///+++++
//////////////////::::///::://///////////////++++++++++++++++++++++++//::::::--------------......:shhyhhhhyso++//oydmmmmmmmmmmmmdhsssshmmmmmNmmNNNNNNNNNNNNNNNNNNNNNNNNmmmdhyo/ssyyyyyyyhhhhhhhysoossssyyyyyyhhyyys++ossssssyyyyyyyyso+ossssssssssyyyhhy+:+oooosssssoossyhhyo:/++oooosssssyyyyhhy+:+ooosssssyyhhy+//++ooooosssssyyyyo//++++ooooosssssyys+/++ooooosssssyyys+/++++oooooossssyyyo//++++++oooooossssso//++++++ooooosso+:/++++++oooooosssss+://++++++++oooooosso//+++ooooooossso//++++++++++oooo+///+++++
+++++++////////////////////////////////////////////////////+/////++///::::------------------.....-ohyyyhhyys++///+shdmmmmmmmmmmmdysssshdmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmdhs/ossyyyyyhhhhhhhhhyoossssyyyyyyhhhhys++ossssssyyyyyyyyso+osoosssssosssyhhyo//+ooosssssooossyhyo:/++oooooosssssyyhys+:/ooossssssyyyy+:/+oooooooossssyyyo//+++++oooooosssyys+:++ooooooossssyys+/++++ooooooossssys+//+++++++ooooooosss+//++++++oooooooo/:/+++++++ooooooosso/://+++++++++oooooso+//+++ooooooossso//++++++++++++o++//++++++
/////////////////::::/::::::::::///////////////////////+++++++////////:::::------------------....-/yysyyhyys+////+shdmmmmddmmmmmdyssosyddmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmmdysssyyyyyyyyhhhhhhyoosssssyyyyyhhhhys++ossssssyyyyyyhyyo/+ooosssssooosyyhyo/:+ooosssysooossyyyo:/++oooooossssssyyys+:/+ooossssssyyy+:/+ooooooossssssyyo//++++++ooooooossss+:/+oooooooossssso+//+++++oooooooosss+:/+++++++ooooooosso+:/+++++++oooooo+/:/++++++++oooooosso/://++++++++++ooooo+//++oooooooooooo+//++++++++++++o+////+++++
/////////////:::::::::::::::::://///////////////++/////+++/++++++++//::::::::::-::--------------.-/syssyyyys+/////oyhdmdmddmmmdddysoosyhddmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhyyyyyyyyyyhhhhhhsossssyyyyyyyyyhhyo/+sssssssssyyyhhyo+/ooosssssooossyyyo/:+ooossssysoossyyso:/++++ooooosssssyyys+-/+ooossssssyys+:/+ooooooossssssyso//++++++ooooooossso+//++ooooooooossso+//++++++ooooooooso/::++++++ooooooooooo/:/+++++++++++oo+/:/+++++++++ooooooo+/://++++++++++oooo+/:/++ooooooooooo+/::/++++++++++++/:://+++++
////::::::://:::::::/::///://////////////////////////////////////////:::::::::--:-------------....:oyssyyyso+///:/oyhdddddddmdddhyooooyhddmmdmmmmNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNmmdyyyyyyyyyyhhhhs+ossssyyyyyyyhhhyo+/ossssssssyyyyyso//+oosssssoooossyys+:/+ooosssssssssyyso/:++oooooooossssyyyo/-/+ooooooosssss+:/+oooooooooossssso///++++++oooooooooo+/:++oooooooooooo+/::/+++o+ooooooooo+/-:/++ooooooooooooo/::/+++++++++++o+/::/+++++++++++++oo+/:-://++++ooo+ooo++/:::/+ooooooooo++/:::://++++++++/::--::///++
:::::::::::::::::::::::::::::::::::::::://////////////////////////::::::--::---:::--------........-/yyssyyso+///::+yhdddddddddddhsoooosyddddddmmmNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmdhyyyyyyyyyhys+ossssssssyyyyhhys+/+osssssssssyyyso//+ooossssooooossss+/:+ooooosossssssso+::/++ooooooooosssso+/-:++oooooosssso+::+ooooooooooosssoo/:/+++++oooooooooo+/:-/+ooooooooooo+/::-://++oooooooo+/::::://++ooooooooo+/::::/+++ooooo+++/::::/++++++++++++++/::::::///++++++///::::::///++++++//::::::::::::::::::::::::::--
:::::::::::::::::::::::::::::::::::::::://///////////////////:://::::::::::---------------------..-/sysssyso+///::+syhdddddddddhhso+++syhdddddmmmNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyyyyyyyyys++oossssssssyyyyys+//osssssssssssyso+/+ooooossooooossso+/:/+ooooooooossoo+/:-:/+ooooooooooooo+/:-:/+oooossssoo+/--/+oooooooooooooo/:-:/++++ooooooooo+/:--::/++ooooo++/:::::::::://///:::::::::::::///+++++//::::::::///+/////::::::::///++++++///::::::::::--::::::::://:::::::::::::://////:::::---:::::::::::::-
::---------:::::::::::::::::::::::::://////////////////////////////:::::::::::::-::---------------.:oysssso+//::::/oyhddddhdddhhys++++syhdddddmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyssyyyyso++ossssssssyyyyyo+//+osssssssssssso+//+oooooooooooosoo+:--//+ooooooooo+//::::://+ooooooooo++/::::::/++ooo+++/:---::/+ooooooooo+//:::::://++++++++//:::::::::::::--:::::::::::::::::---::::://////::::---::::////:::::::---:::::::::::::::--::::://///////:--::::://///////:::::::::////////////::-::::://////::::
/::::::::::::::::-------------:::::::::::::://///:::/::::::://:::::::::::----------..---------.....-+ysosso+//::::/oyhhdddhhddhhyo++++oyhdddddmmmmmmmmmmmmmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhyssssso++ooossssssssssso+/:/oossssssssssoo+:-:/oooooooooooo+/::--::://+++////:::::::::::///////:::::::::::::::::----:::::::::///////::::::::::::::::---:::::::::/:::::---:::://////////::::-:::////////////::-:::://////////::--:::://///////:::---::///+++//++//:-:::://///////////::::///////+++++++/:::::///////////:
//::::::::::::::::::::::::::::::::::::::::::://////////////////:::::::::::::::::-:---------------..-/ssoooo+//::::/oyhhhhhhhddhhyo++++oyhddddddmmmmmmdmmmmmmmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmhyssso+/++oosssssssssso+/::/+oossssssoo++::-:://+oooooo++/:::::::::::----::://///////////::::---::://///////:::---:::::::::::::----:::::////::::::----:::::://////:::---:://////////////::-:://////////////:::://///////////::-:://////////////:-:///+++++++++++::://////////+++///:://///++++ooooo++/::://///++++++++/
::::::::::::::::::::::::::::::::::::::////////////////////////////:::::::::::::::::::::::-----------/ssooo++//::::/osyhhhhhhdhhyso++/++shdddddddmmmmmdmmmmmmmmmmmNmmmNNNNNNNNNNNNNNNNNNNNNNNmmdhso//::/+oooossssoo++/:::::/++oooo++//::::::::::::::--::::://///:::::--::///////+++++/////:---:////////////::--::::://///:::::--:::////////////::--:::::///////////:-:://////+++++++++/:-:///+++++++++++/:::///+++++++++++/::://////++++++++/:-:/++++oooooooo+::////++++++++++++/:://++++ooooooooo+/::///+++++++++++/
:::::::::::::::::::::::::::::::::::::::::::::::::::::::://///:/::::::::::::::::::-------------......:oso++++//::::/osyhhhhhhhhyyso++//+shhhhhdddmmmmddmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmmdy+:::::/++oooo++//::::::::::::::--::://///:/:::::---:://////////:::-:://+/+++++++++++++//:-:://////+/+////:--::///////////::--:://////++++++//:--::///////++++++/:-:////+++++oooo+++/:-:/+++++oooooooo+/://+++++++ooooo+/::///++++++++ooo++:-:/+oooooooooso+:///++++++++++++++:://++++oooooooooo+/://+++++++oooo+++
::::::::::::::::::::::::::::::::::::::::::::/::::://://:::::::::::::::::::::::::::::----------------:+so+++////:::/osyhhhhhyhhysoo+///+syhhhhdddmmmddddmmmmmmmmmmmmmmmmmmmmNNNNmmNNNNNNNNNNNNNNNNmdyoooooooosooooooo+++++++++++++///+++++++++////::-:///////////////:://++++ooooooosoooo+/:-:////+++++o+++//:-::////////////:::::///++++++++++/:--:////++++++oo++/:-:///++++ooooooo+++:-:/+++oooooooooo+::/++++++ooooooo+/::/+++++++ooooooo+:-:++ooooooooooo/:/+++++++++++++++/::/++++oooooooooo+/://++++++ooooooo+/
::::::::::::::::::::::::::::::::::::::::::::///////////////////:::::::::::::::::::-------------.....-+so+++////:::/+syhhhhyyhhyso++///+syhhhhhdddmmddddmmmmmdmmmmmmmmmmmmmmmmmNmmmNNNNNNNNNNNNNNNNmmdhssyyyyyyhyyyysssssssssyyyhhhyyyyyyyyyyyyyysoo+++ooossssssyyyyyssoooooosssssssyyyyso+/:/++++ooossssoo++:://///++++++++//:::///+++++ooooo+/---:///+++++ooooo+/:--//+++++oooooooo+/:-:/++ooooooooooo/::/++++++ooooooo+:://++++++oooooooo+:-:++oooooossso/::/++++++++++++++/:://++++oooooooooo/::/+++++++ooooooo+/
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::----------------....-/oo+//////:::/+syhhyhyyhhyso++///+oyyhhhhdddmmddddmmdmdddmddmddmmmmmmmmmmNmmmmmNNNNNNNNNNNNNNNNNmdhyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhyhhhyhhhhyyyyyyyyyyyyyyyyhyyyhhhhhhhhhhhhhdhhhyssyyyyyyyhhhhyyyyssosssssssssyssssoo+oooooooossssssoo+/+++ooo+oooosooo++/-://+++++ooooooo++/:-:/++oooooooooo+/::/++++oooooooo+/:://++++++ooooooo+/:-:/+ooooooooo+:-:///++++++++++++:::://+++++++oooo+/:-://++++++oooooo+/:
:::::::::::::::::::::::::::::::::::::::::::::::::::::////:///::::::::::::::::::::::::::::-----------:++o+//////:::/+oyhhyyyyyyyo+++///+oyyhhhhdddddddddmdddddddddmdddmmdmmmmmmNmmmmmmNNNNNNNNNNNNNNNNNNmmdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssyyyyyyyyssssssssssssssssssssssssssssssssyyyyssssssssyyyyyyhhyyyyyssooossyysssssssssoo+/:/+oooooooosooo+////++++oooo+++++:-:///++++++oo+oo++/:-:/++++ooo+++/::://////++++++//::-::///++++++++++/:--::////++++++++//:.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--------------..:/+o+//////:::/+osyhyyyyyyso+++///+syyhhhhhdddddhhddddddddmddddddmmdmmmmmmmmmmmmmmNNmNNNNNNNNNNNNNNNNmmdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssyssssssssssssssssyyyyyyyyyyyyyyyyyyyyysssssooosssssssssyssyyssssssssyyysyyyysssssssssyyyyyyyyyyssooooooosssssssooooo+++oooosssssooo++++++++++ooosooo+/////++++++++++///::////////+++++++////
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-------------//++///////:/++osyyyyyyyyso+++///+syyhhhhhdddddhhdmdddddddddddddmdddddmmmmmdmmmmmmNmmNmNNNNNNNNNNNNNNNmdysssssssssssssssssssssssssssssssssssssssssssssssssssssosooossssssssssssssssssooooosssssssssssssooooossssoooooooooooooooosssssssssossoossssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssyyyyyyysyyyysssyssssyyyyyyysysssssssoosssssssssooooooooossssssoooooooooo+++++++o+++++++
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::----------------//++///////:/++osyyyyyssso++++///+syyhyhhhdddddhhdddddddddddddddmmddddmmmmmddmmmmmmmmmmmNNNNNNNNNNNNNNNNmhssssyssyyssssssssssssssssssssssssssoooooooooossoooooooooooooooooooossssssssoooossssssssssssoooooooooossssossoooooooooooooooooo+ooooooooooooooooosssssosssssssssssssssssssssssssssssyyyyysyyyyyyyysyyssyyssssssyyssyyyyyyyyysssssssssyyyyyyyyyyyyyyyyyyyyyssssssssoooooooooooo++o++++++++++++/////////
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--------------...://+++//////:/++osyyyyssoo+++++///+syyhyhhddddddhhddddddddddddddddmdddddmmmmdddmmmmmmmmmmmmmNNNNNNNNNNNNNNmdysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssoossssssssssooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo+oooooooooooo+++++++++++++++++++++++//////////////////////::::::::::::::-------------
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-----------++//++//////::++osyyyysssoo++/////osyyyyyhhddddhhhhdhhhddddddddddddddddddmmmdddmmmmmmmmmmmmmNNNNNNNNNNNNNNNNmdhysssssssssssssoososssssssssssssooooooooooooooooooooooooooooooooossssssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++/////////////////////////::::::::::::::::::::::///////////////////////:::::-----..................
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::-------------:+//++///////:/+osyyyyssooo++/////osyyyyyhhddddhhhhdhhhhddddddddddddddddmmmmdddddmmmmdmmmmmmmmmmmNNNNNNNNNNNNmmmdysoossssssoooooooooooooossoooooo++++++++++++++++++++++++++++oo+++ooo++++++++oo++++++++++++///+++++++++++++++++++++++++++//////////////////////::://///////////////////:::::::::::::::::::::::::::::::::::::::::---::::::::------------::+osyhyysoo+++///////:::::::::::::::::::::--------------
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::------------://:/+/////////+ossyssssoo+++////+osyyyyyhhhhdhhhhddhhhhddddddddddddddddmmmddddddmmmmddmmmmmmmmmmmmmNNNNNNNNNNNmmmdyoooooooooooooooooosooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++/////////////////////////////////////////////////////::::::://////:::::::::::::::::::::::::::::::::---------------------------------.......---:+syhhhyo++/:::------------:::::::::::////////////+++++++///
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::---------------.-:/:/+///////:/+ossysssooo+++////+osyyyyyhhhhhhhhhddhhhhdddddddhdddddddddmmdhddddmmmmddmmmmmmmmmmmmNmNNNNNNNNNNNNNmmdysooooooooooooosso++++++++++///++/+++++++++++++++///////////////////////////////////////////////::::::/://///:::::::////////////:::::::::::::/:/::://:::::::::::::::::::::::-:::-::::::---------------------------------:--:/oyddhss+/::::::::::////////////+++++++++++++++o+oooooooooossss
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--------:/::++////////+ossysssoo++++////+osyyyyyhhhhhhhyhdhhhhhdddhhddhdddddddddmmdhddddmmmddddmmmmmmmmmmmNmNNNNNNNNNNNNNNNNmdhsoooo++++oss++++++++oys++/++++///////////////////////////////////////++++++++++oo++++++++++++++++++++++++++/+++++///////////////////////::::/::::::::::::::::::::::::::::::---:::::::::-:::::::::::::::::::///////////+syddhs+//////////+++++ooooooooosssssssyyyyssssyyyssssssssssssssss
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--------:/::++///////++ossysssoo+++/////+osyyyyyhhhhhhhyhdhhhhhhddhhhhhdddddddddmmdhhddddmmdddddmddmmmmmmmmmmmmNNNNNNNNNNNNNNmmmhsooosyhysyhhhhhhhhhdhhhhhyyo++++++++ooooooooooooooooooooooooooooo+++++++++++++++++++++++++///////////////////////::::::::::::::::::::::::::::::///////////////////////////////////+++///////++/+////++++++++++++++oydddhyo////++ooosssyyyyyyssyyyssssssssssssooooooooooo++++++++++++++
/::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::---------:::/+///////++osssssoo++++/////+osyyyyyhhhhhhyyhdhyyhhhhhhhhhhhddhdhddddddhhdddddmddddmmddmmmmmmmmmmmmmNNNNNNmNNNNNNNNmmmmdhhhhhyyhyyyyyyyhyssyyssyyssooooo++++++++++++++///+/////////////////////////////////////:::::::::::::::://///::::////////////////++++++++++++++++++++++++++++++o+++++++++++++o+++ooooooooooooooooossssssssssssyhdddyso+++++oooosoooooooooooooooooooooooooooooooooooooooooooooooooooo
o+///:::::::::::::::::::::::::::::::::::::::////:::::///::::::::::::::::::::::::::::::::::::----------::-/++//////+++osssooo++++/////+osyyyyyhhhhhhyyhhhyyhhhhhhhhhhhdhhhhddddddhhddddddddddddddmdmmmmmmmmmmmmmNNNNmNNNNNNNNmNNmmmmdddddddddddhhho++++///////////////////////+++++++++++++++++++++++++++++ooooooo++++oooooooooooosssssooooosssssssssssssssssssssssssssssssssoossssssooosssssssssssssssssssssssssssssssssssssssoossooooooooosyhddhso++++++++++++++ooo++oooooooooooooooooooooooooo++++++++++//////////
//////:::::::::::::::::::::::::::::::::::::::::/::::::://///::///////:::::::::::::::::::::::::::::----::-:++//////+++oossooo++++/////+oyyyyyyhhhhhyyyhhyyyyhhhhyyyyhhhhhhhdddddhhhhdhddddddddddddddmmmmmmmmmmmmmmNNmmNNNNNNNmNNNmmmdhhhhhhhhhyo//////++++ooooosssssssssssyyyyyhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssyyssssssssssssssssssssosooooooooooooooooo+oo++++++++++++++++oshdhso+++++++++oooooooooooooo+++++++++++++///////////////////////////////:
:::::::::::::::::::::::://::::::::::::::::::::::::::::::::::::::///:::::://:::::::::::::::::::::::-----::-/++/////++++osoooo++++/////+syyssyyhhyhyyyyhhyyyyyhhhyyyyyhhhhhhdddddhhhhdhhddddddddddddddddmmdmmmmmmmmNmmmmNNNNNNNNNNNmmmdyyyyyysys++++++ooooosssssssssssyyyyyyyyyyyyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyssyyyyyyyyyyyyysssssyyyyyyyyyyyysyyysssssssssssssssssoooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++yhyo+///////////////////////////////////////:::::::::::::::::::------------
///////////////////::::://////////////::::::::::::::::/:::::/:::::::::::://::::::::::::::::::::::------::-/++////:/+++oooooo++++/////+sssssyyyyyyyyyyhyyyyyyyhyyyyyyhhhhhhhddddhyhhhhhhhhddddddddddddddmdddmmmmmmmmmmmmNNmNNNNNNNmmmmdhysssyyyoooooossssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++/++++/////////////////+yds/://::///////::::::::::::::::::::::-----------------::::::::::::::///////
::::::::::::::::::::::::/::::::////////://///////::::::::::://///////////::::::::::::::::::::::::-------:::++////:/++ooooooo+++++////+sssssyyyyyyyyyyhysyyyyyyysyyyyhhhhhhhddhhyyyhhhhhhhdddddhdddddddddddddmmmmmmmmmmmmNmmNNmmNNNmmmmmmhyssyhysosssssssssssssssssssssssssssssssoosso+oooossooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++////////////////////////////////////////////////::::::::::::::+yds::::::::::::::----------------------:::///++++ooooooooooo+oooooooooooooooo
:::::::::::::::::::::::::::/::::////////://////////////////////////::////////////:::::::::::::::--------:::/+//////+++oooooo+++++////+sssssyyyysyyyyyhysyyyyyyysysyyyyyyhhhdhhhyyyyhhhhhhhdhhhhhhhdddddddddddmdmmmmmddmmmmmmmmmmmmmNNmmmmmhyyyhsoooooooooooo++++++++++++++++++++++++++/+++++++oooooooooossoosooooooooooooooooooooo+oooo++o+++++++++++++++//////////////////:://::://////////////////////+++++++++++++++++++++++++++++oydy/:://++oooooo+ooo++o+++++++++++oooooooooooooooooooooooooooooosooossssssssoo
------:::::::::::::::::::::::::::::::::::://:::////////////////////:////////:::://:::::::::::::::::::----::/++/////++++oooooo++++///+ossssssyyssyyssyhyyyysyyysssssyyyyyyhhhhhyyyyyyhhhhhhhhhhhhhhddhddddddddddmmmddddmmmmmmmmmmmmmNNmmmNNmmddhho++++++++++++oo+++++oooooooooooooooossssssssssssssssssssssssyyysssssssyyyyyyysyyyyyyyssssyysyyysssssssssssosssssssssssoooo++///+++ossssssssssssssssyyysssyssssssssssssssssssssssssoo+sdh+++ooosssssssssssssssssssoooooooo+++oooooooooooossssssssssssssoooo+++///////
---------::::::::::::::::::::::::::::::::::::::::::::::::/:/::::::::::::/:::::::::::::::::::::::::::::----::+++////+++++ooooo++++///+ossosssssssyyssyysssssyyyssssyyyyyyyhhhhyyssyyyhhhhhhhhhhhhhhdhhhddhddddddddmddddmmmmmmmmmmmmmmmmNmNNNmmmdysooooossssssssssssssssssssssyysssssyyyyyyyyyyyyyyyyyyyyyyyyyyyhhyyyyyyyyyyyysssssssssssoosssoooossossssssooosssssssyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssyyyyyyysssoo++hdsoooo+oooooo++o++++++o+++++ooooooossssssssssssooooooo++++++/////////////+++++
--------------::::::::::::::::::::::::--:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--:----:/++/////++++ooooooo+++//++oososssssosyyssyyssssssyyssssyyyyyyyyhyyyyssyyyhhhhhhhhhhhhhhhhhhddhhdddddddmdddddmmmmmmmmmmmmmmmmmNNNmmmmhyysssyyyyyyyyyyyyyyyyyyyyhhhhhhhhhyyyyyyyyyyyyyyyyyssssssssssssssoooooooooossoosooooooooossssssyyyyyyyyyyyysyyyssssssssoosooooooooooooooooooossssyyyyyyyyyysyyyssyssssssssssoo+++///sdho+++++++++++oooooooooosssssoooooooo+++++++++//////////////+++//++++++++++////
----------------------------::::::::-----------:::::::::::::::::::::::::::::::::::::::::::::::::::---------:///////++++++oooooo++/++++osssssssosyysyyyssssssyssssssyyyssyyyyyysssyyyyhhhhhhhhhhhhhhhhhddhhhddddddddddddddddmmmmmmmmdmmmmNNmmmmmmhyyyyyyyyyyyyyyyyssssssssssssooooooooooooooooooooooooosooosoooossssssssssssyyssyssyyyyssssssssssssssssooooooooooooooo++++ooooooossssssssssyyyyyysyyyssssoooooooo+++++++++++++///////ydyooooooooooooooooo++++////////::///////////////++/++++////////////////////////
----------------------------------------------------------:::::::::::::::::::::::::::::::::::---------------////////+++++oooooo+//++o+ossosssoosssssysssssssysssssyyysssyyyyyysssyyyyhhyyyyyhhhhhhhhhhhhhhhhdddddddddddddddmmmmmmdddmmmNmmmmmmmmdoooooooooooooooooooooooooooooooosoossssssssssssssssssysssssssssoossssoooooooooooooo+++++oo+++++++ooooooooooooooosssssssssssoooooooooooooo++++++++++++++++++++++ooo+oooooooo++//+++oydyoo++++++////////::::///:///////////////////////////////://////////////////:::
-------------------------------------------......-----------------------------:::::::::---------------------:///////++/+++oo+++++++oooosoossooosssssyssssssssssssssyyssssyyyyysssyyyyhyyyyyyyyyhhhhhhhhhyhhhhhhdddddhdddddddmdddddddddmmmmmmmmmmdyo++ooooooooooooooooooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++////++++++oo++ooooooooooo+ooooooo++++++++++++++++++++++++++++++ooo++oooooooooooo+++o++++++////////ydy+//////////////////////////////::::::::/::/:///////////::/:/:::::::::-:::----
--------------------------------------............-----------------------------------------------------------/:::////++/+++++++++++oooosssssoooossssssssssssssssssyyyssssssyyyssyyyyyyysyyyyyyyyyhyyhhhyyhhhhhhhhhhhhhddddddddddddddddmmmmmmmmmmdy++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++///////////////////+++++++++++++++++o+++++o++++++++++++///////////////////////////odho/////////////////////////////:::::::::::::::::::::------------.........`````
-........----------------------------............------------------------.......----.-----...--.............-:---::::/+/+//++++++++oooosssssooooosssssssssssssssssyyssssssssyyssyyyyyyysyyyyyyyyyyyyyyyyyyyhhhhhhhhddhhddhhddddddddddddmmmmmmmmmmho++/+++++++++++++++++++++++++++++++++//+++++//////////////////////////////////////////////////////////////////+++++++++++++++++++++++++///////////////////////////////////////////+ydh+////////////////::::::::----------.........``````````````                  
-........-----------------------------...........----------------------------................................------:::///+++++/++++o+ooossssoooossssssssssssssssssyyssssssssssssysssyysssysyyyyyyyyyyyyyyyyyhhhhhhhhhhhdhhhhhddddddddddmddmdmddmmhs++++/++++++++++++++++++++++++++++///////////////////////////////////////////////////////////////////////////////////////////////////////////////////:::::::::::::::::::::::::--:::ohdh:------..........```````````````````````                       ````````````
.......----...--------------------------............------------------------------..................`````````.------.--://///////++++oooooooooooososssssssssssssssyyssssssssssssssssyysssssysysyyyyyyyyyyyyyyyyhhyhhhhhhhhhhhhdddddddddddddddddddho//::--:////////////////////////////////////////////////:://////////////////////////////////////////////////////////::::::::::::::-------------........````````````````````````````.sdd-                              ```..--..```````````````````......---:::://+
---------......------------------------.--.........-----------------------......-------.................................-:::::::://+++ooooooooooooosssssssssssssssyyssssssssssssssssyssssssysysyyyyyyyyyyyyyyyyyyyyyyyhhyhhhhhdddddddhdddddddddddho:------::::::::::::::::::::::::::::::::::----------------------------------------------------------................``````````````                                                 `-yd+`             ```````````````````..-/+/////:-----:::///++oossssyyyyyhhhhhh
---------........----------.........................--...---....................--.....................................`..--------:/+++ooooo+o++ooosssssssssssssssssssssssssssssssssyssssyyssssyysyyyysyyyyyyyyyyyyyyyhhyhhhhhhhdddhhhdhhdddddhddh+.`````.``............`.......````````````````````````````````````````````````````                                                                                     ``````````````/hh+-.```````````..........-----::::-..-/+osooooosyyhhhhhhhhhhhhddddhhhdhhhhd
---------...........------...................................................................................``````````````......`.://+++++++++++oooooossssssssssssssossssssssssssssysssssyssssyssysyysyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhy/                                                                                                                               ````````````````````````````````````````...........---+hhho::://///+++oooossssyyyhhhhhhddhyssoooo+osyhhhdddddddddddddddddddddddddh
-------..........................................................................................`````````.````````````````````````.://+//+//++++++ooooooosossssosssooosssssssssssssyssyssssssssyyyyyssyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhy-                                                                                        ``  ```````````````````````````````````````````...............---....--::////+++oooossssyyyyyyhhhhhhhhhddddddddddddddddddddddddddddddddhysyhhdddddddddddddddddddddddddddh
--..-......................................................................................```````..````````````````````````````````.-:/:::::/+//++++++ooooooooooooooooossssosssssssyssysssssssssssyyssyyyyyyyyyysssyyysyyyyyyhhhhhhyyyhhyyhhyyhyo.                                                      ``````````````````````````````````````````................---------:::::://////++++ooooosssssyyyyyy+:/oyhhhdddddddddddddddddddddddhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
--...........-........................................................................`.....```````````````````````````````````````````-----.-::://////++++++++++ooo++ooooooooooossssssssssssssssyssyssyyyyssyysssssyyyyyyyyyyyhhhhyyyyyyyyyyyyhy+`                       ````````````````````````````````````...............--------::::::://////++++++oooosssssyyyyyyyhhhhhhhdddddddddddddddddddddddddddddy++shddddddddddddddddddddddddddddhhdddddddddddddddddddddddddddddddddhddddddddddddddddddddddddddddddddddd
-....-...................................................`...........................````````````````````````````````````````````````````.```..------:::///::////++++++++++++oooooososssssssssssssssssssyyysyyyyssssyyyyyyyyyyyhyyyyyyyyyyhyyhyys-````````````````````````````.................--------::::///++++ooooosssssyyyyyyyhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhyssyhdddddddddddddddddddddddddddhhhddddddddddddddddddddddddddddddddddddddddhddddddddddhhhhhhhhdddddddd
---.............----........................................`..``....................``.```````````````````````````````````````````````````   `````````.......--:::::///////://+++oo+oooooooosssssssssssssssyyyysssyyssyyyyyyyhhyyyyyyyyyyhhhhhs:``.`...........--------::::::////++++oooossssyyyhhhhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdddddddddddddddddddmddddddddddddddhyyyyyhhddddddddddddddddddmmmddhyhddddmdddddddddddddddddddddddddddddddddddddddddddddddhdddddddddddd
-------..--......-------............................................```.....```..........````````````````````````````````````````````````                     ```............-::///////+++++o++oooooooosssssssssssssssssyyyyyhhhhhyyyssyyhhyyyo:-:::///+++oooosssyyyyyyhhhhhhhdddddddddddddddddddddddddddddddddddddddmmmddddddddddddddddddmmmmmmmmmmdddddddmmmdddmmmmmmmmmmmmmmmmmmddddmmmmmmmmmmmmmmmmmmddmmmddddddddhhyyyyyhhddddddddddmmmdddmdhhyyhddddmdddmmmmdddddddddddddddddddddddddddddddddddddddddddddddddd
------------------..-----..--...................................................``.........```.````````````````````````````````````````                                      ``.....----::://////////++++oooooooooooo+ossssyyhhhhyyo:-:///oyhhhhhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmmdddhhhhhhhhhdddddmmdmmmdddhysyyhddddmmmddddddmmmdddddddddddddddddddddddddddddddddddddddddd
---------------------------------..................................................```..............```````````````````````````````````                                               ```````....----:::////++++/::::::/++oosssyyso-``...-oddddddddddddddddddddddddddddddddddddddddddddddddddddddmmddddmmmmmdddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddhhhhhhhhddddddddhhyyyyhhddddmmmmmmmmdddddddddddddddddddddddddddddddddddddddddd
--------------------------------------..------.......................................................```````````````````````````````````                                                            ````..------` ``  ```..--:::::-.---::/sdmmdmmmmmmmmmmdddddddddddddddddddddddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddhhhhhhhhhhdhhyysssyyhhdddddddddddddddddddddddddddddddddddddddddddddddd
